# Generated by Django 4.0.4 on 2022-04-24 15:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(130), django.core.validators.MinValueValidator(15)])),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('occupation_type', models.CharField(choices=[('P', 'Private'), ('G', 'Govt'), ('S', 'Self work'), ('U', 'Unemployed')], max_length=3)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voters', to='locations.block')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_voters', to=settings.AUTH_USER_MODEL)),
                ('panchayat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voters', to='locations.panchayat')),
            ],
            options={
                'verbose_name': 'Voter',
                'verbose_name_plural': 'Voters',
            },
        ),
    ]
