# Generated by Django 4.0.4 on 2022-05-01 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panchayat',
            options={'ordering': ['name', 'block__name', 'constituency__name'], 'verbose_name': 'Panchayat', 'verbose_name_plural': 'Panchayats'},
        ),
        migrations.AlterField(
            model_name='panchayat',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panchayats', to='locations.block'),
        ),
        migrations.AlterField(
            model_name='panchayat',
            name='constituency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='panchayats', to='locations.constituency'),
            preserve_default=False,
        ),
    ]
